### PR TITLE
Rename Pulsar to Hiro

### PR DESCRIPTION
**Pull request by ospfranco**
Changing the name worked without a problem. There is one place where the old name is present, which is the [script for generating the update manifest](https://github.com/nchapman/pulsar/blob/develop/scripts/updateManifest.cjs#L57). As soon as we migrate Repos we need to change those, and since we are going to release soon, it should probably be soon too.

### CODE REVIEW

**Comment by ospfranco** [comment]
OSP 000400
OSP 000401

There seem to be some errors on the typescript of the adjusted nebula types that prevent building, @Warefoxe can you take a look?

**Comment by demetrxx** [comment]
image

I have the following error when starting the app

**Comment by demetrxx** [comment]
Should we change the db name? It will erase all the data. WatermelonDB hasn't yet implemented migrations for that.

**Comment by nchapman** [comment]
> Should we change the db name? It will erase all the data. WatermelonDB hasn't yet implemented migrations for that.

Let's do name the db to `hiro` going forward, but I'm okay if that means we just reset everyone's databases as part of this name change since it's really just us that are effected. Otherwise we end up with code that hangs around to check and rename it on boot and that feels unnecessary.

**Comment by nchapman** [comment]
> There is one place where the old name is present, which is the [script for generating the update manifest](https://github.com/nchapman/pulsar/blob/develop/scripts/updateManifest.cjs#L57).

As we discussed in the meeting, we'll leave this until we move/rename the repo.

**Pull request merged**
